# Generated by Django 3.0.2 on 2020-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
    ]
